# Run the app; mount /var/run/docker.sock or use Portainer env
version: "3.8"
services:
  dashboard:
    image: node:18-alpine
    container_name: docker-dashboard
    working_dir: /app
    restart: unless-stopped
    ports:
      - "${PORT:-1713}:1713"
    environment:
      - USE_PORTAINER=${USE_PORTAINER}
      - PORTAINER_URL=${PORTAINER_URL}
      - PORTAINER_ENDPOINT_ID=${PORTAINER_ENDPOINT_ID}
      - PORTAINER_API_KEY=${PORTAINER_API_KEY}
      - DOCKER_SOCKET=${DOCKER_SOCKET}
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: sh -c "npm install && npm start"
