services:
  dashboard:
    build: .
    container_name: docker-dashboard
    ports:
      - "1714:1714"
    environment:
      - DOCKER_SOCKET=/var/run/docker.sock
      - USE_PORTAINER=${USE_PORTAINER}
      - PORTAINER_URL=${PORTAINER_URL}
      - PORTAINER_ENDPOINT_ID=${PORTAINER_ENDPOINT_ID}
      - PORTAINER_API_KEY=${PORTAINER_API_KEY}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
