services:
  dashboard:
    build: .
    container_name: docker-dashboard${DEV_MODE:+-dev}
    ports:
      - "1714:1714"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=1714
      - DOCKER_SOCKET=/var/run/docker.sock
      - USE_PORTAINER=${USE_PORTAINER:-false}
      - PORTAINER_URL=${PORTAINER_URL:-}
      - PORTAINER_ENDPOINT_ID=${PORTAINER_ENDPOINT_ID:-}
      - PORTAINER_API_KEY=${PORTAINER_API_KEY:-}
      # qBittorrent integration (optional)
      - QBITTORRENT_URL=${QBITTORRENT_URL:-http://qbittorrent:8080}
      - QBITTORRENT_USERNAME=${QBITTORRENT_USERNAME:-admin}
      - QBITTORRENT_PASSWORD=${QBITTORRENT_PASSWORD:-adminadmin}
      # Authentication (set AUTH_ENABLED=true to enable)
      - AUTH_ENABLED=${AUTH_ENABLED:-false}
      - AUTH_USERNAME=${AUTH_USERNAME:-admin}
      - AUTH_PASSWORD=${AUTH_PASSWORD:-admin}
      - SESSION_SECRET=${SESSION_SECRET:-docker-dashboard-secret-change-in-production}
      # CORS (comma-separated list of allowed origins, or * for all)
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-*}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Development mode: mount code for hot-reloading (only if DEV_MODE=true)
      # These volumes are ignored in production
    command: ${DEV_COMMAND:-node server/index.js}
    restart: unless-stopped
    networks:
      - docker-dashboard
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - "com.docker.dashboard.managed=true"
      - "com.docker.dashboard.version=1.0"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:1714"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  
  # Override service for development mode only
  dashboard-dev:
    extends: dashboard
    container_name: docker-dashboard-dev
    environment:
      - NODE_ENV=development
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./server:/app/server
      - ./public:/app/public
      - ./package.json:/app/package.json
    command: npm run dev
    profiles:
      - dev

networks:
  docker-dashboard:
    driver: bridge
    name: docker-dashboard-network
