# Run the app; mount /var/run/docker.sock or use Portainer env
version: "3.8"
services:
	dashboard:
		build: .
		container_name: docker-dashboard
		restart: unless-stopped
		ports:
			- "${PORT:-1713}:1713"
		environment:
			- USE_PORTAINER=${USE_PORTAINER}
			- PORTAINER_URL=${PORTAINER_URL}
			- PORTAINER_ENDPOINT_ID=${PORTAINER_ENDPOINT_ID}
			- PORTAINER_API_KEY=${PORTAINER_API_KEY}
			- DOCKER_SOCKET=${DOCKER_SOCKET}
		volumes:
			- /var/run/docker.sock:/var/run/docker.sock:ro
		# Uncomment below to disable direct socket and use Portainer gateway only
		# volumes:
		#   - /dev/null:/var/run/docker.sock
