services:
  dashboard:
    build: .
    container_name: docker-dashboard
    ports:
      - "1714:1714"
    environment:
      - NODE_ENV=production
      - PORT=1714
      - DOCKER_SOCKET=/var/run/docker.sock
      - USE_PORTAINER=${USE_PORTAINER:-false}
      - PORTAINER_URL=${PORTAINER_URL:-}
      - PORTAINER_ENDPOINT_ID=${PORTAINER_ENDPOINT_ID:-}
      - PORTAINER_API_KEY=${PORTAINER_API_KEY:-}
      # qBittorrent integration (optional)
      - QBITTORRENT_URL=${QBITTORRENT_URL:-http://qbittorrent:8080}
      - QBITTORRENT_USERNAME=${QBITTORRENT_USERNAME:-admin}
      - QBITTORRENT_PASSWORD=${QBITTORRENT_PASSWORD:-adminadmin}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    networks:
      - docker-dashboard
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - "com.docker.dashboard.managed=true"
      - "com.docker.dashboard.version=1.0"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:1714"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  docker-dashboard:
    driver: bridge
    name: docker-dashboard-network
