name: 🐛 Bug Report
description: Report a bug or issue with Docker Dashboard
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below.
        
  - type: textarea
    id: description
    attributes:
      label: 🐛 Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true
      
  - type: textarea
    id: steps
    attributes:
      label: 📋 Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
      
  - type: textarea
    id: expected
    attributes:
      label: ✅ Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should happen...
    validations:
      required: true
      
  - type: textarea
    id: actual
    attributes:
      label: ❌ Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happens...
    validations:
      required: true
      
  - type: textarea
    id: screenshots
    attributes:
      label: 📸 Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: Drag and drop images here...
      
  - type: input
    id: version
    attributes:
      label: 📦 Dashboard Version
      description: What version of Docker Dashboard are you using?
      placeholder: e.g., 2.0.0, latest, commit hash
    validations:
      required: true
      
  - type: dropdown
    id: os
    attributes:
      label: 💻 Operating System
      description: What OS are you running Docker Dashboard on?
      options:
        - Linux (Ubuntu/Debian)
        - Linux (CentOS/RHEL)
        - Linux (Arch)
        - Linux (Other)
        - macOS
        - Windows (WSL2)
        - Windows (Docker Desktop)
    validations:
      required: true
      
  - type: input
    id: docker-version
    attributes:
      label: 🐳 Docker Version
      description: Run `docker --version` and paste the output
      placeholder: e.g., Docker version 24.0.5
    validations:
      required: true
      
  - type: input
    id: browser
    attributes:
      label: 🌐 Browser
      description: Which browser are you using?
      placeholder: e.g., Chrome 120, Firefox 121, Safari 17
    validations:
      required: true
      
  - type: dropdown
    id: auth-enabled
    attributes:
      label: 🔐 Authentication Status
      description: Do you have authentication enabled?
      options:
        - Authentication Disabled (default)
        - Authentication Enabled
    validations:
      required: true
      
  - type: textarea
    id: logs
    attributes:
      label: 📜 Container Logs
      description: Run `docker compose logs` and paste relevant logs
      placeholder: Paste logs here...
      render: shell
      
  - type: textarea
    id: additional
    attributes:
      label: 📝 Additional Context
      description: Add any other context about the problem here
      placeholder: Any other information that might help...
      
  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Pre-submission Checklist
      description: Please verify these before submitting
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported
          required: true
        - label: I have included steps to reproduce the bug
          required: true
        - label: I have included my environment details (OS, Docker version, browser)
          required: true
        - label: I have checked the container logs for errors
          required: true
