blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/MNDL-27/docker-dashboard/wiki
    about: Check our comprehensive wiki documentation
  - name: 💬 Discussions
    url: https://github.com/MNDL-27/docker-dashboard/discussions
    about: Ask questions and discuss ideas with the community
